### ISSUE TITLE
No virtual method addOnTabSelectedListener

### ISSUE THREAD

**Issue by tusharr1996** [AppLozic/Applozic-NativeScript-Chat-Plugin#15]
I'm using Applozic SDK on the fresh nativescript 5.4 project. The conversation list screen opens perfectly but when I try to start a new conversation using plus button it throws the following error.

`System.err: java.lang.NoSuchMethodError: No virtual method addOnTabSelectedListener(Landroid/support/design/widget/TabLayout$OnTabSelectedListener;)V in class Landroid/support/design/widget/TabLayout; or
its super classes (declaration of 'android.support.design.widget.TabLayout' appears in /data/app/org.nativescript.chatTest-bSK2RsiVtSiX1tG3pWKE0Q==/base.apk)
System.err:     at com.applozic.mobicomkit.uiwidgets.people.activity.MobiComKitPeopleActivity.onCreate(MobiComKitPeopleActivity.java:167)
System.err:     at android.app.Activity.performCreate(Activity.java:7149)
System.err:     at android.app.Activity.performCreate(Activity.java:7140)
System.err:     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1288)
System.err:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3017)
System.err:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3172)
System.err:     at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
System.err:     at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
System.err:     at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1906)
System.err:     at android.os.Handler.dispatchMessage(Handler.java:106)
System.err:     at android.os.Looper.loop(Looper.java:193)
System.err:     at android.app.ActivityThread.main(ActivityThread.java:6863)
System.err:     at java.lang.reflect.Method.invoke(Native Method)
System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)`

**Comment by Sunilkumarr** [comment]
Hello,
We have fixed this in our older version of the native script plugin. You can use the latest version of the native script  [link](https://docs.applozic.com/docs/nativescript-installation#install-chat-plugin). 

Feel free to reopen if have any query on this.
