### ISSUE TITLE
Callbacks are not executed in function launchChatWithGroupId for iOS

### ISSUE THREAD

**Issue by lcini17** [AppLozic/Applozic-NativeScript-Chat-Plugin#17]
In **applozic-chat.ios.js** the function **launchChatWithGroupId** accepts a successCallback and an errorCallback as part of the input parameters. However, these callbacks are never executed.

On the other hand, for Android, the given callbacks for the same function are executed as expected.

**Comment by Sunilkumarr** [comment]
Thanks for finding out. 
We will add the callback for successCallback, errorCallback in the next release.

**Comment by Sunilkumarr** [comment]
@lcini17 This has been released in our latest version of the native script you can use the latest version.

**Comment by lcini17** [comment]
Thank you :)
