### ISSUE TITLE
AppCrash on backbutton from launchGroupChat on Android

### ISSUE THREAD

**Issue by argia-andreas** [AppLozic/Applozic-NativeScript-Chat-Plugin#23]
App is crashing on android when trying to hit the back button on a group chat launched with launchGroupChat(groupId)
Any ideas?

The Back button on on launchChat() works fine.

Thank you.

```console
System.err: java.lang.ClassNotFoundException: org.nativescript.nativescript_applozic_chat.NativeScriptActivity
System.err: 	at java.lang.Class.classForName(Native Method)
System.err: 	at java.lang.Class.forName(Class.java:400)
System.err: 	at java.lang.Class.forName(Class.java:326)
System.err: 	at com.applozic.mobicomkit.uiwidgets.conversation.activity.ConversationActivity.onSupportNavigateUp(ConversationActivity.java:334)
System.err: 	at androidx.appcompat.app.AppCompatActivity.onMenuItemSelected(AppCompatActivity.java:203)
System.err: 	at androidx.appcompat.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:109)
System.err: 	at androidx.appcompat.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:109)
System.err: 	at androidx.appcompat.widget.ToolbarWidgetWrapper$1.onClick(ToolbarWidgetWrapper.java:188)
System.err: 	at android.view.View.performClick(View.java:5637)
System.err: 	at android.view.View$PerformClick.run(View.java:22429)
System.err: 	at android.os.Handler.handleCallback(Handler.java:751)
System.err: 	at android.os.Handler.dispatchMessage(Handler.java:95)
System.err: 	at android.os.Looper.loop(Looper.java:154)
System.err: 	at android.app.ActivityThread.main(ActivityThread.java:6119)
System.err: 	at java.lang.reflect.Method.invoke(Native Method)
System.err: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
System.err: Caused by: java.lang.ClassNotFoundException: Didn't find class "org.nativescript.nativescript_applozic_chat.NativeScriptActivity" on path: DexPathList[[zip file "/data/app/io.grafstrom.online-1/base.apk"],nativeLibraryDirectories=[/data/app/io.grafstrom.online-1/lib/x86, /data/app/io.grafstrom.online-1/base.apk!/lib/x86, /system/lib, /vendor/lib]]
System.err: 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
System.err: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
System.err: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
System.err: 	... 17 more
```

**Comment by Sunilkumarr** [comment]
@argia-andreas Seems like there is an issue getting the parent activity package of`NativeScriptActivity` you can try this below for a workaround now will fix it in one of our release 

1. Open the `AndroidManifest.xml` from the folder `platforms/android/app/src/main/AndroidManifest.xml`
  
    once the file is open find the tag  ` <manifest xmlns:android="http://schemas.android.com/apk/res/android"`
     add this below config right below the manifest tag
	`xmlns:tools="http://schemas.android.com/tools"`

Finally, it will look like this:

     <manifest xmlns:android="http://schemas.android.com/apk/res/android"
	xmlns:tools="http://schemas.android.com/tools"


  2. Add the activity under the tag <application in the same AndroidManifest.xml file


        	<activity
			android:name="com.applozic.mobicomkit.uiwidgets.conversation.activity.ConversationActivity"
			android:label="@string/app_name"
			android:parentActivityName="com.tns.NativeScriptActivity"
			android:theme="@style/ApplozicTheme"
			tools:node="replace">
			
			<meta-data
				android:name="android.support.PARENT_ACTIVITY"
				android:value="com.tns.NativeScriptActivity" />
		</activity>

**Comment by argia-andreas** [comment]
@Sunilkumarr Thank you.

That seems to have fixed the issue.
