### ISSUE TITLE
Publish the package on npm

### ISSUE THREAD

**Issue by mariano-aguero** [AppLozic/Applozic-NativeScript-Chat-Plugin#5]
Hello, could you publish the package in npm? Is not working. 
Currently it does not exist, and the integration method is a bit complicated. Clone the repository in local, then make tns plugin add DIRECTORY. It's a bit cumbersome

![daaglapxcaai5sb](https://user-images.githubusercontent.com/1144028/38386145-25f5fce4-38ea-11e8-931c-0d02379b9c95.jpg)

Thanks in advance

**Comment by gabitoesmiapodo** [comment]
+1

**Comment by ygilliot** [comment]
Please publish the plugin on npm **and** NativeScript Marketplace. It will be easier for NativeScript devs to discover it.

**Comment by gabitoesmiapodo** [comment]
Good! Thank you!
